### ISSUE TITLE
Run Failed

### ISSUE THREAD

**Issue by zunlihu** [ranga543/terraform-docs-scrape#3]
Hi,
I just want to use the index.ts to scrape my data from terraform. But I cannot succeed to do that. Follwing errors occurs when I run in vscode.
![image](https://user-images.githubusercontent.com/21325921/41721952-d15778ec-7599-11e8-985f-6072a5cab8ec.png)

**Comment by ranga543** [comment]
Latest changes should fix this and closing out, if you still having issue you can open new issue.
